### ISSUE TITLE
Gitlab download fails starting at 7.4.3

### ISSUE THREAD

**Issue by spuder** [spuder/puppet-gitlab#100]
If gitlab_download_link parameter is not supplied, then this puppet module will attempt to download from the default url. This makes it really easy for end users to install gitlab since they only need to supply a version(e.g 7.4.3) and not a full blown url. 

Unfortunately gitlab changed their download links when they started including gitlab-ci

Before
https://downloads-packages.s3.amazonaws.com/centos-6.5/gitlab-7.4.3_omnibus.1-1.el6.x86_64.rpm

Now
https://downloads-packages.s3.amazonaws.com/centos-6.6/gitlab-7.4.3_omnibus.5.1.0.ci.1-1.el6.x86_64.rpm

Not sure this can be fixed. 

The work around is to manually set the download_url, however that will require setting two parameters in the puppet module. It will require the user to lookup the new url every time they upgrade gitlab. 

Before

```
class { 'gitlab':
  gitlab_branch => 7.4.0,
  external_url    => 'http://gitlab.example.com',
}

```
After
```
class {'gitlab':
  gitlab_branch => 7.4.3,
  external_url    => 'http://gitlab.example.com',
  gitlab_download_link => 'https://downloads-packages.s3.amazonaws.com/centos-6.6/gitlab-7.4.4_omnibus.5.1.0.ci.1-1.el6.x86_64.rpm',
}
```
The best option would be to try and bribe the gitlabhq guys to place symlinks with their rpm artifacts. 

    gitlab-7.4.3_omnibus.1-1.el6.x86_64.rpm => gitlab-7.4.3_omnibus.5.1.0.ci-1-1.el6.x86_64.rpm

**Comment by joakimkarlsson** [comment]
There seem to be a yum repo setup at https://packages.gitlab.com/gitlab/gitlab-ce

**Comment by spuder** [comment]
Yes however the package cloud puppet module is quite broken right now. #150

**Comment by spuder** [comment]
Module transitioned to here:  https://github.com/vshn/puppet-gitlab
