### ISSUE TITLE
OracleLinux support

### ISSUE THREAD

**Issue by hjjacobs** [spuder/puppet-gitlab#110]
As stated on https://about.gitlab.com/downloads/ the Omnibus installer is supported on OracleLinux.
After a minor modification (adding 'OracleLinux' to the operatingsystem case in packages.pp) Gitlab CE is successfully installed using this puppet module on OracleLinux 6.5. Also updating the installed version works fine.

What is necessary to officially add OracleLinux support to this puppet module?

**Comment by spuder** [comment]
This should be easy to add. 

- add to metadata.json
- update init.pp to not throw warning on oracle linux
Optional:
- add a test to spec directory to test download of package (I assume it is the same package as for centos/RHEL)
- update vagrant file with a oracle linux box

Feel free to make a merge request.
