### ISSUE TITLE
Duplicate declaration for openssh-server

### ISSUE THREAD

**Issue by kostyrevaa** [spuder/puppet-gitlab#114]
Hello!
For all of my hosts in production I use puppetforge module for configuring ssh.
but when I want to use your module alongside I get this nasty:

    Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[openssh-server] is already declared in file /etc/puppet/environments/production/modules/ssh/manifests/server/install.pp:7; cannot redeclare at /etc/puppet/environments/production/modules/gitlab/manifests/packages.pp:73 on node gitlab.example.org
Isn't modules suppose to be independent from each other?

**Comment by spuder** [comment]
Yes, the module supports both people with exisitng modules, and those who have no modules ( masterless puppet). 

You want to set the following parameter

     puppet_manage_packages => false

This will skip the packages.pp file and should fix your issue with duplicate ssh hosts.

**Comment by kostyrevaa** [comment]
thanks! I missed that parameter, sorry.

**Comment by spuder** [comment]
No problem, others have run into the same issue.
