### ISSUE TITLE
Puppet Forge Module Outdated

### ISSUE THREAD

**Issue by rilindo** [spuder/puppet-gitlab#120]
It looks like the Puppet Forge module release is several releases behind the upstream. Are there any plans to push out the current upstream release to Puppet Forge?

**Comment by spuder** [comment]
Yes, I will push a new version once the regression tests start passing. It will be a few weeks at least. 

In the mean time, I'd recommend using r10k and pointing the remote to the github url.

**Comment by spuder** [comment]
Pushed 2.3.6 to the forge. You can see further updates in the gitter chat https://gitter.im/spuder/puppet-gitlab
