### ISSUE TITLE
no way to specify timezone

### ISSUE THREAD

**Issue by kostyrevaa** [spuder/puppet-gitlab#121]
one can specify a correct timezone as pointed out in https://github.com/gitlabhq/gitlabhq/pull/8015#issuecomment-72840835

**Comment by spuder** [comment]
Thanks for reporting this. If you want to create a pull request adding a new parameter, we could pull it in. I've added this to the feature request backlog.

**Comment by spuder** [comment]
This has been merged in and is available on the puppet forge. Thanks
