### ISSUE TITLE
when redirect_http_to_https is false the template gitlab-puppet.rb.erb ignores  ssl_certificate parameter

### ISSUE THREAD

**Issue by timhughes** [spuder/puppet-gitlab#126]
```
<% end %><% if @redirect_http_to_https == true -%>
nginx['redirect_http_to_https'] = <%= @redirect_http_to_https %>
nginx['ssl_certificate'] = '<%= @ssl_certificate -%>'
nginx['ssl_certificate_key'] = '<%= @ssl_certificate_key %>'
<% end -%>
```

This should probably be dependent on the ```external_url``` parameter starting with ```https```

**Comment by erik-stephens** [comment]
+1 and for some context on why: gitlab ci runners with buggy ssl support or out-of-date CA bundles.

**Comment by erik-stephens** [comment]
Actually, this doesn't look like a puppet-gitlab issue but an [issue with how the gitlab::nginx chef recipe interprets the url](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/nginx.md#redirect-http-requests-to-https).

**Comment by timhughes** [comment]
@erik-stephens see the pull request. In nutshell, if you dont "redirect_http_to_https" then you dont deploy ssl certs. 

My use case is that I run apache on port 80 so I set "redirect_http_to_https = False" so that nginx doesn't listen on port 80. This causes the erb template to not include ssl certificates. My merge #127 request fixes the logic around this and also includes tests that cover what I believe the logic should be.

**Comment by erik-stephens** [comment]
@timhughes Looks good to me.  Not sure what I was linking to.

**Comment by spuder** [comment]
Module transitioned to here:  https://github.com/vshn/puppet-gitlab
