### ISSUE TITLE
Feature Request: Enable parameters to use external resources

### ISSUE THREAD

**Issue by cdenneen** [spuder/puppet-gitlab#129]
Postgres,
Redis,
etc.

This allows leverage of existing services to be used as backend for GitLab.
Also allows for use of RDS in Amazon.

**Comment by spuder** [comment]
I don't think this is possible with gitlabs current architecture. All services are bundled in with omnibus. For example, the gitlab.rb file lets you specify different ports for redis & postgres , but not different hosts for those services. 

If you want to use external services, you probably will need to build gitlab from source.

**Comment by cdenneen** [comment]
According to gitlab docs it would just be a matter of modifying few yaml files. Now the package would/could install services but probably could be disabled?
Maybe need to open ticket with gitlab directly?

**Comment by spuder** [comment]
If it is possible to modify the gitlab.rb file to use an external redis instance, then you can set `puppet_manage_config` false and add that configuration line yourself. 

However, I don't see any options around that in their omnibus installation instructions. I'm pretty sure you will need to install from source, or open a feature request with gitlabhq

**Comment by cdenneen** [comment]
opened: https://github.com/gitlabhq/gitlabhq/issues/8989

Even if installer did install then this module could override the config/database.yml and config/resque.yml to add external hosts to connection info no?

**Comment by spuder** [comment]
This module doesn't modify those files directly. With omnibus installs, the omnibus service reads the contents of the gitlab.rb file and then it modifies the database.yml and resque.yml files. Everything is now abstracted through the gitlab.rb unless you install from source.
