### ISSUE TITLE
Create backup before upgrading releases

### ISSUE THREAD

**Issue by spuder** [spuder/puppet-gitlab#138]
When a user switches branches to install a newer version, the puppet module should first run a one off backup.

**Comment by poikilotherm** [comment]
I don't think this is really necessary, as on the installation of the RPM-package (dunno for the DEB) this is already done by the pre-install script.

**Comment by ahuffman** [comment]
According to the gitlab docs @ "https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/update.md", "This is a 'light' backup that only backs up the SQL database".  

A full backup, especially when using an automation tool, would be much safer than relying on the light SQL backup in the pre-upgrade scripts.

**Comment by olhado** [comment]
I agree, adding this would be awesome!

**Comment by spuder** [comment]
Module transitioned to here:  https://github.com/vshn/puppet-gitlab
