### ISSUE TITLE
git_data_dir not affecting gitlab config

### ISSUE THREAD

**Issue by rickard-von-essen** [spuder/puppet-gitlab#144]
This is similar to #84.

The attribute ```git_data_dir``` is written by the template to the config file as an assignment:
```ruby
git_data_dir = '/opt/repos'
```
But it only affects the config if it is written as a function call:
```ruby
git_data_dir '/opt/repos'
```

I reviewed the template and didn't see any other occurrences (besides ```external_url```) of ruby function calls.

**Comment by spuder** [comment]
Thanks!
