### ISSUE TITLE
Running puppet agent -t to update gitlab configuration tries to download and install gitlab again

### ISSUE THREAD

**Issue by olhado** [spuder/puppet-gitlab#152]
Running: Gitlab EE 7.10.4, CentOS 6.6

We installed successfully, but were trying t omodify the configuratioon (add a new setting), and when we re-run `puppet agent -t`, the run failed, complaining that it couldn't update ensure status from absent to latest, and then displayed the rpm command output, which obviously printed that gitlab was already installed.

Any ideas? Is this because the ensure is set to latest, instead of installed?

**Comment by spuder** [comment]
Gitlab changed the names of their packages when they released 7.1.x. which this module depended on. 

There are several bug tickets open on this. 
#141 
#150 
#149 
#140 

Unfortunately it is going to take a major refactor to handle the way that gitlab changed their package names. 

Issue #140 has a pull request that might fix this, but I haven't tested it yet.

**Comment by olhado** [comment]
Sorry, didn't quite understand that those issues were the same.

**Comment by spuder** [comment]
No problem. I think people who aren't using puppet will run into the same issue.
