### ISSUE TITLE
package gitlab-ce-7.10.0~omnibus.3-1.x86_64 is already installed

### ISSUE THREAD

**Issue by Thubo** [spuder/puppet-gitlab#155]
Hi there,

I'm trying to install gitlab from you puppet module, however it only installs the package, nothing else, in the next run I get an error, as the packages is (correctly) already installed.

```
[root@gitlab ~]# puppet agent --test
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for gitlab.example.com
Info: Applying configuration version '1432280363'
Notice: /Stage[main]/Gitlab::Install/Exec[download gitlab]/returns: executed successfully
Notice: /Stage[main]/Gitlab::Install/Package[gitlab]/ensure: created
Notice: Finished catalog run in 22.17 seconds
[root@gitlab ~]# puppet agent --test
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for gitlab.example.com
Info: Applying configuration version '1432280396'
Error: Could not update: Execution of '/bin/rpm -i /var/tmp/gitlab-ce-7.10.0~omnibus.3-1.x86_64.rpm' returned 1: package gitlab-ce-7.10.0~omnibus.3-1.x86_64 is already installed
Error: /Stage[main]/Gitlab::Install/Package[gitlab]/ensure: change from absent to latest failed: Could not update: Execution of '/bin/rpm -i /var/tmp/gitlab-ce-7.10.0~omnibus.3-1.x86_64.rpm' returned 1: package gitlab-ce-7.10.0~omnibus.3-1.x86_64 is already installed
Notice: Finished catalog run in 1.92 seconds
```

here are the settings I'm using: (ENC)

```
  gitlab:
    external_url: http://gitlab.example.com
    gitlab_branch: 7.10.0
    gitlab_download_link: file:///root/gitlab-ce-7.10.0~omnibus.3-1.x86_64.rpm
    puppet_manage_backups: 'true'
    puppet_manage_config: 'true'
    puppet_manage_packages: 'true'
```

I also tried using the 7.11.1 Version of gitlab-ce which gives the same error.

Running gitlab-ctl reconfigure after the puppet run gives me a working setup, however the settings provided via puppet are ignored completely (which is a result of the failing rpm command).

I found #152 and it's attached issues, however it seems there is no solution yet?!

Did I miss something? Is there a (temporary) workaround/fix available?

Thanks for your help

**Comment by spuder** [comment]
Gitlab completely overhauled their packaging on version 7.10 and changed their download links and package names. 

This breaks the puppet module. You can follow issue #140 and issue #150 for updates. 

Fortunately gitlab finally included a repo hosted on package cloud, however it is also broken. 

We are working on overhauling the puppet module, but we need gitlab to get their act together and fix the repo first.
