### ISSUE TITLE
validate package url to sanitize %7E

### ISSUE THREAD

**Issue by poikilotherm** [spuder/puppet-gitlab#156]
This is basically a reminder to myself. Will likely provide a PR for it.

I had a mistake in my class config with a package url including a %7E for ~, as I copy'n'pasted the link from Firefox into Hiera.

This lead to strange "already installed" errors for the package. Validating the URL before using it for the package name or validating the package name to include correct chars should beware people from falling in this pitfall.

**Comment by spuder** [comment]
Module transitioned to here:  https://github.com/vshn/puppet-gitlab
