### ISSUE TITLE
Revision 3.0.x

### ISSUE THREAD

**Issue by spuder** [spuder/puppet-gitlab#157]
Change the puppet module to use the following: 

- Use ahuffman's changes to use package cloud repos
- Use elastic/elasticsearch model to dynamically create gitlab.rb based on hash. Reducing the number of parameters down to a dozen.

**Comment by spuder** [comment]
https://packages.gitlab.com/gitlab/gitlab-ce/install

**Comment by olhado** [comment]
Any chance EE will be supported?

**Comment by mikec-bullhorn** [comment]
Any chance ee will be supported, now that the access scheme has changed?

**Comment by spuder** [comment]
Yes, just found out that gitlab finally added gitlab-ee packages to package cloud. I don't have an enterprise license, so I need to research how to implement this (is it a serial number, product key) ect..

Do you know how gitlab ee is activated?

**Comment by mikec-bullhorn** [comment]
The release blog post:

https://about.gitlab.com/2015/05/22/gitlab-7-11-released/

To install the license, vist /admin/license in your GitLab instance as an
admin. Here you can upload your .gitlab-license file, which will instantly
unlock GitLab Enterprise Edition.

Basically, you upload the license you get from gitlab itself into the app.

On Wed, Jun 3, 2015 at 4:41 PM, Spencer Owen <notifications@github.com>
wrote:

> Yes, just found out that gitlab finally added gitlab-ee packages to
> package cloud. I don't have an enterprise license, so I need to research
> how to implement this (is it a serial number, product key) ect..
>
> Do you know how gitlab ee is activated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spuder/puppet-gitlab/issues/157#issuecomment-108609031>
> .
>



-- 

*Michael Chmielewski** |* Practice Lead, Release Engineering

*T* 617.478.9368

-- 
 <http://www.bullhorn.com>

Twitter <https://twitter.com/bullhorn> | Linkedin 
<http://www.linkedin.com/company/bullhorn> | Facebook 
<https://www.facebook.com/Bullhorn>

<http://www.bullhorn.com/engage/>

**Comment by mikec-bullhorn** [comment]
Have you published a branch for this? I'd love to look at it, and maybe even help here and there.

**Comment by spuder** [comment]
I haven't pushed a branch yet because of the problem with the packagerepo puppet module. Thanks for letting me know about vshn's module. This does look exactly like what I was wanting to do with branch 3.x

**Comment by ahuffman** [comment]
I wouldn't cross your fingers about the packagecloud ever being fixed.
I've been using my forked packagecloud branch since 7.10 with my forked
puppet-gitlab repo and it's been working just fine.  Feel free to pull in,
and/or rework anything that I did there as well as the process to install
the newer gitlab packages.


On Wed, Jul 8, 2015 at 11:15 AM, Spencer Owen <notifications@github.com>
wrote:

> I haven't pushed a branch yet because of the problem with the packagerepo
> puppet module. Thanks for letting me know about vshn's module. This does
> look exactly like what I was wanting to do with branch 3.x
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spuder/puppet-gitlab/issues/157#issuecomment-119620996>
> .
>



-- 
Regards,

Andrew

**Comment by spuder** [comment]
Module transitioned to here:  https://github.com/vshn/puppet-gitlab
