### ISSUE TITLE
Package['wget'] already declared

### ISSUE THREAD

**Issue by bjwschaap** [spuder/puppet-gitlab#158]
For version <= 2.3.6: When using multiple classes (modules) on the same server (=server role), the package declaration for wget can also be made elsewhere, resulting in:

`
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[wget] is already declared; cannot redeclare at /etc/puppetlabs/puppet/environments/core/modules/gitlab/manifests/install.pp:183
`

The correct way to implement the download would be to support both curl as well as wget. As a workaround you could test for the package declaration using stdlib defined().

**Comment by bjwschaap** [comment]
Sorry, I see it's already fixed.

**Comment by spuder** [comment]
This module is currently undergoing an overhaul because gitlab changed their package names. Soon it shouldn't even require curl or wget because they finally added repos.

**Comment by spuder** [comment]
The module doesn't yet work with the 7.10.x releases of gitlab, only 7.0.x
