### ISSUE TITLE
high_availability_mountpoint option fails on latest stable branch

### ISSUE THREAD

**Issue by andrakis** [spuder/puppet-gitlab#159]
Hello,

So I'm trying to use the latest stable branch of GitLab, 7-12-stable.
I'm also trying to use the high_availability_mountpoint option.

I receive the following error message:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: high_availability_mountpoint is only available in gitlab >= 7.2.0, found '7-12-stable' at /etc/puppet/modules/gitlab/manifests/init.pp:1010 on node gitlab.internal.alliancesoftware.com.au
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I believe the issue is that versions 7.10 and higher are considered to be lower version numbers than 7.9 and lower.

The naming convention of the branches differs from the versioning system used, and causes the versioncmp to behave differently to what we're expecting.

**Comment by spuder** [comment]
Gitlab changed their packages in gitlab 7.10 which completely breaks this module. The gitlab package is now hosted in package cloud, and has different names. 
There is an overhaul in the works planned in #150 and #140

**Comment by andrakis** [comment]
Thank you for that, I'd looked through some issues but hadn't noticed those.

If older releases still work, I'll use them for now and will keep an eye on the overhaul progress.

Cheers
