### ISSUE TITLE
Support for setting Rails environment variables

### ISSUE THREAD

**Issue by bjwschaap** [spuder/puppet-gitlab#160]
Since gitlab v6 it's possible to set Rails environment variables to set e.g. proxy etc. that will be picked up by Gitlab's backing processes. See: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/environment-variables.md

It would be nice to set these through a module parameter.

**Comment by spuder** [comment]
Module transitioned to here:  https://github.com/vshn/puppet-gitlab
