### ISSUE TITLE
So you can vouch for vshn's module?

### ISSUE THREAD

**Issue by olhado** [spuder/puppet-gitlab#163]
I trust your opinion. Have you looked at his module, does it look good?

**Comment by spuder** [comment]
Yes, I was working on a rewrite that used the package cloud repos. In the redesign I tried to use the package cloud repos with the package cloud puppet module. 
Unfortunately the package cloud puppet module is very broken, so I was trying to implement using bare yum repo / apt packages. vshn wrote his module almost exactly how I was going to refactor this one.

https://github.com/vshn/puppet-gitlab/blob/master/manifests/install.pp#L13-L44
