### ISSUE TITLE
Add unicorn config options

### ISSUE THREAD

**Issue by spuder** [spuder/puppet-gitlab#37]
Add flags that allow you to configure the following settings in the unicorn.rb

worker_processes 2
timeout 30 (I think I already enabled this in 1.3.0, but double check)

**Comment by dblessing** [comment]
@spuder I think this is a pretty critical configuration option, especially the ability to configure workers. We're experiencing issues now with merge requests and need to increase workers to fix it. Without this configuration option we cannot. Can you reopen this, please?

**Comment by spuder** [comment]
I've reopened this. It will be a little while before I can work on this myself. If there is a pull request, I could merge it in right away.

**Comment by spuder** [comment]
Module transitioned to here:  https://github.com/vshn/puppet-gitlab
